const resumeData = {
  personal: {
    name: "Aishwarya Dattatray Joshi",
    phone: "+1-(458)272-8696",
    email: "aishwarya.joshi111298@gmail.com",
    linkedin: "https://linkedin.com/in/aishwarya-joshi11",
    github: "https://github.com/Aishwarya-Joshi11",
  },

  education: [
    {
      degree: "M.S. in Computer Science",
      institution: "Oregon State University",
      location: "Corvallis, OR, USA",
      startDate: "Sep 2024",
      endDate: "Jun 2026",
      gpa: "3.82/4",
      coursework: [
        "Machine Learning",
        "Deep Learning",
        "Data Analysis",
        "Algorithms: Design, Analysis and Implementation",
        "Parallel Programming",
        "Artificial Intelligence Capstone Project",
      ],
    },
    {
      degree: "B.E. in Computer Engineering",
      institution: "P.E.S's Modern College of Engineering",
      location: "Pune, India",
      startDate: "Aug 2017",
      endDate: "Jul 2021",
      gpa: "3.7/4",
      coursework: [
        "Artificial Intelligence",
        "Machine Learning",
        "Object Oriented Programming",
        "Database Management System",
        "Data Structures and Algorithms",
        "Software Engineering and Project Management",
      ],
    },
  ],

  experience: [
    {
      role: "System Software Engineer Intern",
      company: "Intel Corporation",
      location: "Remote, USA",
      type: "Internship",
      startDate: "Jun 2025",
      endDate: "Present",
      bullets: [
        "Automated SQL Server standalone deployments with Ansible, replacing a 20-minute 6-step manual setup with single-command execution; reduced engineer effort by 85% and ensured consistent environment provisioning.",
        "Automated 2-node SQL Server cluster installations using Ansible, implementing shared disks, failover nodes, and active/passive roles; reduced cluster setup time by 40% and improved high-availability deployment repeatability.",
        "Developing and evaluating a CPU utilization forecasting and anomaly detection pipeline using LSTM, LSTM+Attention, and Prophet to predict system load up to one week ahead and enable proactive infrastructure monitoring (ongoing).",
      ],
    },
    {
      role: "Software Developer",
      company: "Digital Experience (UIT), Oregon State University",
      location: "OR, USA",
      type: "On-Campus Employment",
      startDate: "Nov 2024",
      endDate: "Jun 2025",
      bullets: [
        "Resolved critical website issues in account access, application submission, and form processing, reducing average ticket resolution time by 25% and improving student satisfaction.",
        "Designed and optimized Salesforce solutions using Apex and Lightning Web Components (Flows: screen/record-trigger), enhancing workflow automation and improving system efficiency by 20%.",
      ],
    },
    {
      role: "Senior Software Engineer",
      company: "Persistent Systems Limited",
      location: "Pune, MH, India",
      type: "Full-time",
      startDate: "May 2021",
      endDate: "May 2024",
      bullets: [
        "Built and optimized cloud solutions using REST APIs and AWS services such as DynamoDB, Lambda, S3, API Gateway, Workspaces, and EC2, lowering infrastructure costs by 30% and accelerating solution reliability by 45%.",
        "Streamlined data pipelines from AWS S3 to Snowflake using Stage and Storage Integration objects with Python and SQL, boosting data processing speed by 60% and eliminating 10 hours of manual work per week.",
        "Implemented usage-reminder alerts for inactive and long-running AWS Workspaces, reducing idle resource consumption by 30% and saving around $500 per month in cloud costs.",
      ],
    },
  ],

  projects: [
    {
      title: "AI-Powered Grant Matching Platform",
      tags: ["LLMs", "Vector Search", "Agentic AI"],
      startDate: "Sep 2025",
      endDate: "Ongoing",
      github: "https://github.com/woonki94/grant-matching-agent/tree/main",
      bullets: [
        "Built a two-stage retrieval pipeline (pgvector ANN search + LLM reranking) using Amazon Titan embeddings and Claude Haiku, reducing candidate search space by over 90% while improving match relevance.",
        "Designed a parallel LLM processing pipeline executing chunked LLM calls concurrently, reducing end-to-end response time by ~70% compared to sequential execution.",
        "Architected an agentic AI workflow using LangGraph and LangChain to automate faculty profile ingestion, CV publication extraction, grant retrieval, and match justification generation.",
      ],
      techStack: ["LangGraph", "LangChain", "pgvector", "Amazon Titan", "Claude Haiku", "PostgreSQL"],
    },
    {
      title: "Object Detection and Instance Segmentation",
      tags: ["Deep Learning", "Mask R-CNN"],
      startDate: "Jan 2025",
      endDate: "Mar 2025",
      github: "https://github.com/Aishwarya-Joshi11/Object_detection_instance_segmentation_Mask_RCNN",
      bullets: [
        "Engineered a GPU-optimized training pipeline in PyTorch for Mask R-CNN (ResNet-101 + FPN), improving detection accuracy by 15% and reducing training loss by 35% through data augmentation and hyperparameter fine-tuning, achieving benchmark-level mAP on the COCO dataset.",
      ],
      techStack: ["PyTorch", "Mask R-CNN", "ResNet-101", "FPN", "COCO dataset"],
    },
    {
      title: "Air Quality Index Prediction",
      tags: ["Machine Learning", "Random Forest"],
      startDate: "Aug 2020",
      endDate: "Jun 2021",
      github: "https://github.com/AQI-BE-Project/AQI_using_flask",
      bullets: [
        "Developed an end-to-end Random Forest regression pipeline (R² = 0.87) combining real-time WAQI feeds and CPCB historical data, improving forecast precision by 18%, cutting prediction error by 30%, and deploying via a Flask CI/CD workflow with a color-coded dashboard that boosted user efficiency by 60%.",
      ],
      techStack: ["Python", "Random Forest", "Flask", "CI/CD", "WAQI API", "CPCB data"],
    },
  ],

  skills: {
    coreSkills: [
      "Machine Learning",
      "Deep Learning",
      "NLP",
      "LLM Systems",
      "Agent AI",
      "Vector Search",
      "Distributed Systems",
      "Scalable Systems",
      "Time-Series Forecasting",
      "Web Development",
    ],
    languages: [
      { name: "Python", level: "Proficient" },
      { name: "Java", level: "Working Knowledge" },
      { name: "SQL", level: null },
      { name: "HTML", level: null },
    ],
    frameworksAndTools: [
      "PyTorch",
      "scikit-learn",
      "Pandas",
      "NumPy",
      "Prophet",
      "LangChain",
      "LangGraph",
      "Flask",
      "REST APIs",
      "AWS (EC2, S3, Lambda, API Gateway, WorkSpaces, Bedrock)",
      "Snowflake",
      "PostgreSQL",
      "pgvector",
      "SQLAlchemy",
      "Ansible",
      "SQL Server",
      "Git",
      "JIRA",
      "Postman",
      "CI/CD",
      "BeautifulSoup",
      "pdfminer",
    ],
    operatingSystems: ["Windows", "Linux", "macOS"],
  },
};
